---
- name: This sets up an httpd webserver
  hosts: localhost
  vars_prompt:
    - name: "server"
      prompt: "Which server do you want to install?"
      private: no
    - name: "source"
      prompt: "Which source is this?"
      private: no

  tasks:
  - name: Install the httpd server
    yum: name={{ server }} state=present
  - name: Template a file to index.html.j2
    template:
      src: index.html.j2
      dest: /var/www/html/Babu_index.html
  - debug:
      msg: Source {{ source }}
