---
- name: This sets up an httpd webserver
  hosts: web
    server: httpd

  tasks:
  - name: Install the httpd server
    yum: name={{ server }} state=present
  - debug:
      msg: Source {{ source }}
